### ISSUE TITLE
Join table custom primary key problem.

### ISSUE THREAD

**Issue by anvarulugov** [php-activerecord/activerecord#13]
Dear developers,
Thank you for such a good package. I found it very useful. But I am facing to a problem on using `has_many` `through` relationship, exactly I cannot set join table primary key. Could you check if the following lines are correct?

https://github.com/php-activerecord/activerecord/blob/126660b2a6205103524aabca9816e87b94609ab3/lib/Relationship.php#L369

I managed to work the relation only after editing those line into this:

```
if ($using_through) {
       $foreign_key = $join_table->pk[0];
       $join_primary_key = $join_table->pk[0];
} else {
       $join_primary_key = $this->foreign_key[0];
       $foreign_key = $this->primary_key[0];
}
```
I couldn't find examples on documentation on how to set values of those (`$foreign_key `, `$join_primary_key`) variables.

**Comment by shmax** [comment]
Sorry for the long delay! Did you ever fix your problem?

**Comment by shmax** [comment]
I don't seem to go into that area of code in my app, either, but I'm sure you're right. If you want to open a PR I'll stamp it (I'm still working on getting tests working...)

**Comment by ipundit** [comment]
anvarulugov's solution for the if branch does not make sense as `$foreign_key` will always equals `$join_primary_key`:

```
if ($using_through) {
       $foreign_key = $join_table->pk[0];
       $join_primary_key = $join_table->pk[0];
} else {
...
}
```

As far as I can tell without any way to test this, the fix is:

```
if ($using_through) {
    $join_primary_key = $this->primary_key[0];
    $foreign_key = $this->foreign_key[0];
} else {
    $join_primary_key = $this->foreign_key[0];
    $foreign_key = $this->primary_key[0];
}

```

But, I'm unwilling to commit without testing it.

The proper fix would be to first fix issue #22, and then write a test case based on [the `has_many` `through` documentation](https://www.phpactiverecord.org/projects/main/wiki/Associations#has_many_through) to exercise the `if ($using_through)` branch.

**Comment by shmax** [comment]
Sounds good. Let's see how far we can get in resurrecting the tests.

**Comment by ipundit** [comment]
test/HasManyThroughTest.php exercises the if ($using_through) branch with several test cases and it passes regression as is. Changing the code would introduce a bug. [anvarulugov](https://github.com/anvarulugov)'s bug cannot be reproduced without more details. Recommend that this bug report be closed as 'abandoned'.

**Comment by shmax** [comment]
Sounds good, thanks.

@anvarulugov feel free to reopen, but you might want to wait until the release of v2.0, which is coming soon.
