### ISSUE TITLE
Error with spl_autoload_register() in ActiveRecord.php 

### ISSUE THREAD

**Issue by kevin-belanger** [php-activerecord/activerecord#16]
According this PHP 8 migration document:
https://www.php.net/manual/en/migration80.incompatible.php 

spl_autoload_register() will now always throw a TypeError on invalid arguments, therefore the second argument (do_throw) is ignored and a notice will be emitted if it is set to false .

**Comment by shmax** [comment]
Fixed in 924d078bac9445d60ed29d2ddaa8e87e71f834fd
