### ISSUE TITLE
PHP 8+ Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given 

### ISSUE THREAD

**Issue by AVBIT** [php-activerecord/activerecord#17]
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in ...php-activerecord/ActiveRecord.php:43

`$root .= DIRECTORY_SEPARATOR . implode($directories, DIRECTORY_SEPARATOR);`

https://www.php.net/manual/en/function.implode.php
8.0.0 | Passing the separator after the array is no longer supported.
7.4.0 | Passing the separator after the array (i.e. using the legacy signature) has been deprecated.

**Comment by ipundit** [comment]
This bug is already fixed in the latest version and and should be closed.

ActiveRecord.php line 47 already has:

$root .= DIRECTORY_SEPARATOR . implode(DIRECTORY_SEPARATOR, $directories);

**Comment by shmax** [comment]
Will take your word for it, thank you
