### ISSUE TITLE
Problem with DateTime::getLastErrors in Connection.

### ISSUE THREAD

**Issue by cosinus90** [php-activerecord/activerecord#19]
Hello, about the code

```
        $errors = \DateTime::getLastErrors();

        if ($errors['warning_count'] > 0 || $errors['error_count'] > 0) {
            return null;
        }
```

It make a warning of 

E_WARNING[2]: Trying to access array offset on value of type bool at ...ActiveRecord/lib/Connection.php line 527

When no errors. Quote from php.net
`Returns array containing info about warnings and errors, or false if there are neither warnings nor errors.`
https://www.php.net/manual/en/datetimeimmutable.getlasterrors.php

**Comment by shmax** [comment]
PRs welcome

**Comment by ipundit** [comment]
From https://www.php.net/manual/en/datetimeimmutable.getlasterrors.php
Before PHP 8.2.0, this function did not return false when there were no warnings or errors. Instead, it would always return the documented array structure.

So the fix is:

        $errors = \DateTime::getLastErrors();

        if (is_array($errors) && ($errors['warning_count'] > 0 || $errors['error_count'] > 0)) {
            return null;
        }

**Comment by shmax** [comment]
Can please you open a PR? Thank you...

**Comment by shmax** [comment]
I merged and released your proposed fix. Thanks much.

https://github.com/php-activerecord/activerecord/releases/tag/v1.1.8
