### ISSUE TITLE
Submit to Packagist for Composer support

### ISSUE THREAD

**Issue by ipundit** [php-activerecord/activerecord#20]
For those of us who use the Composer package manager, we don't see the latest updates of this revived project. https://packagist.org/packages/php-activerecord/php-activerecord references the old, abandoned project. If I knew that this project was revived, I would have submitted my patches to this repository rather than keeping them private to track with the latest versions of PHP. If this revived project deploys to Composer so that it can live as part of my dev cycle, then you may have another developer who is willing to keep this project alive.

**Comment by shmax** [comment]
Ah, I had no idea it had gone missing. I'll look into it this evening, thank you

**Comment by shmax** [comment]
This form seems to be available under the "php-pattens" namespace:

https://packagist.org/packages/php-patterns/activerecord

Does it work for you?

**Comment by ipundit** [comment]
Yes, you can close this issue now. Verified that `composer update` works

**Comment by shmax** [comment]
Beautiful, thanks much.
