### ISSUE TITLE
Test suite is broken

### ISSUE THREAD

**Issue by ipundit** [php-activerecord/activerecord#22]
The PHPUnit test suite is broken due to missing files:

D:\activerecord\test>d:\activerecord\vendor\bin\phpunit ActiveRecordCacheTest.php

Fatal error: Uncaught Error: Class "DatabaseTest" not found in D:\activerecord\test\ActiveRecordCacheTest.php:5
Stack trace:
#0 D:\activerecord\vendor\phpunit\phpunit\src\Util\FileLoader.php(66): include_once()
#1 D:\activerecord\vendor\phpunit\phpunit\src\Util\FileLoader.php(49): PHPUnit\Util\FileLoader::load('D:\\activerecord...')
#2 D:\activerecord\vendor\phpunit\phpunit\src\Runner\StandardTestSuiteLoader.php(43): PHPUnit\Util\FileLoader::checkAndLoad('D:\\activerecord...')
#3 D:\activerecord\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(146): PHPUnit\Runner\StandardTestSuiteLoader->load('D:\\activerecord...')
#4 D:\activerecord\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(111): PHPUnit\Runner\BaseTestRunner->loadSuiteClass('D:\\activerecord...')
#5 D:\activerecord\vendor\phpunit\phpunit\src\TextUI\Command.php(119): PHPUnit\Runner\BaseTestRunner->getTest('D:\\activerecord...', Array)
#6 D:\activerecord\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#7 D:\activerecord\vendor\phpunit\phpunit\phpunit(107): PHPUnit\TextUI\Command::main()
#8 D:\activerecord\vendor\bin\phpunit(122): include('D:\\activerecord...')
#9 {main}

and

D:\activerecord\test>d:\activerecord\vendor\bin\phpunit ExpressionsTest.php

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in D:\activerecord\lib\Model.php on line 375

Fatal error: Uncaught Error: Class "SnakeCase_PHPUnit_Framework_TestCase" not found in D:\activerecord\test\ExpressionsTest.php:9
Stack trace:
#0 D:\activerecord\vendor\phpunit\phpunit\src\Util\FileLoader.php(66): include_once()
#1 D:\activerecord\vendor\phpunit\phpunit\src\Util\FileLoader.php(49): PHPUnit\Util\FileLoader::load('D:\\activerecord...')
#2 D:\activerecord\vendor\phpunit\phpunit\src\Runner\StandardTestSuiteLoader.php(43): PHPUnit\Util\FileLoader::checkAndLoad('D:\\activerecord...')
#3 D:\activerecord\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(146): PHPUnit\Runner\StandardTestSuiteLoader->load('D:\\activerecord...')
#4 D:\activerecord\vendor\phpunit\phpunit\src\Runner\BaseTestRunner.php(111): PHPUnit\Runner\BaseTestRunner->loadSuiteClass('D:\\activerecord...')
#5 D:\activerecord\vendor\phpunit\phpunit\src\TextUI\Command.php(119): PHPUnit\Runner\BaseTestRunner->getTest('D:\\activerecord...', Array)
#6 D:\activerecord\vendor\phpunit\phpunit\src\TextUI\Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#7 D:\activerecord\vendor\phpunit\phpunit\phpunit(107): PHPUnit\TextUI\Command::main()
#8 D:\activerecord\vendor\bin\phpunit(122): include('D:\\activerecord...')
#9 {main}

**Comment by shmax** [comment]
Heh, okay, I'll take a look tomorrow. Thanks for all the input, it's very much appreciated.

**Comment by ipundit** [comment]
Fixed in PR #25 and PR #34
