### ISSUE TITLE
Deprecation errors in PHP 8.2

### ISSUE THREAD

**Issue by ipundit** [php-activerecord/activerecord#23]
Running php-activerecord in PHP 8.2 generates these deprecation warnings:

Deprecated: Creation of dynamic property ActiveRecord\Validations::$klass is deprecated in D:\EazyPlanet\localhost\utils\vendor\php-patterns\activerecord\lib\Validations.php on line 98

Deprecated: Use of "static" in callables is deprecated in D:\EazyPlanet\localhost\utils\vendor\php-patterns\activerecord\lib\Model.php on line 1554

**Comment by shmax** [comment]
Thanks for the fix!
