### ISSUE TITLE
Change org name?

### ISSUE THREAD

**Issue by shmax** [php-activerecord/activerecord#3]
@jacoz I looked into submitting this project to packagist.org today, but it seems that the vendor name "php-activerecord" has already been taken (by the other project that this is a fork of). There doesn't seem to be any way to create a vendor name manually--packagist seems to derive it from a github path.

I'm going to do a little more research, but would you have any objection to changing the organization name to something else? I was thinking of "php-patterns". What do you think?

**Comment by jacoz** [comment]
fine for me!

**Comment by shmax** [comment]
It turns out all I had to do was change the vendor name in the composer.json file, so I think we're all set. Closing...
