### ISSUE TITLE
Getting / setting attributes should be case insensitive

### ISSUE THREAD

**Issue by ipundit** [php-activerecord/activerecord#35]
Currently,

$model->attrCamelCase != $model->ATTRCAMELCASE != $model->attrcamelcase

even though MySQL and Postgres's table attributes are case insensitive. The test suite works around this problem by strtoupper() attributes for the model fixtures. This is better to be implemented in the Model.php class itself so that users don't have to reinvent this wheel over and over again.

**Comment by shmax** [comment]
Fixed in https://github.com/php-activerecord/activerecord/pull/36, thank you.
