### ISSUE TITLE
Model::__isset($attribute_name) needs overriding when using with Slim/Twig

### ISSUE THREAD

**Issue by hising** [php-activerecord/activerecord#8]
I have found that when using Twig and Slim (Twig v1.2 and Slim v 2) that I need to override the below linked method in order to not having Twig throwing errors when PHPActiveRecord models is not converted `to_array`. My solution (which I found somewhere else) is to extend the Model and use my own Model. The override looks like this:

```
class Model extends ActiveRecord\Model {
  public function __isset($attribute_name) {
    if(parent::__isset($attribute_name))
      return true;

    // check for getters
    if (method_exists($this, "get_${attribute_name}"))
      return true;

    // check for relationships
    if (static::table()->has_relationship($attribute_name))
      return true;

    return false;
  }
}
```

Give me a ping if you would like me to add a PR for it.

Mentioned code:
[Model::__isset($attribute_name)](https://github.com/php-activerecord/activerecord/blob/6706c64c6e8fae294496bf334c079da08cf80198/lib/Model.php#L361)

**Comment by shmax** [comment]
Sure, please open a PR!

**Comment by shmax** [comment]
Be sure to start with a commit that has a test that illustrated the broken behavior...

**Comment by shmax** [comment]
@hising I went ahead and took a crack at this. Please review the PR when you get a chance.

**Comment by shmax** [comment]
Fixed in https://github.com/php-activerecord/activerecord/pull/9
